# Numpy 라이브러리
•빅데이터의 수학적, 과학적 계산을 위해 만들어진 라이브러리 

•반복문 없이 전체 데이터의 연산이 가능한 표준 수학 함수들을 제공

•※배열: 같은 자료형의 값들이 연속적인 형태로 구성된 자료 구조로 다량의 데이터를 그룹으로 관리하고 계산하기 위해 사용!

In [2]:
#numpy 라이브러리를 불러와서 np로 지칭하겠다.
import numpy as np

In [3]:
list1 = [1,2,3,4,50]
list1


[1, 2, 3, 4, 50]

In [4]:
arr =np.array(list1)
arr

array([ 1,  2,  3,  4, 50])

In [5]:
type(arr)

numpy.ndarray

## 일차원배열

In [6]:
arr = np.array([1,2,3,5,"야호"])
arr

array(['1', '2', '3', '5', '야호'], dtype='<U11')

# 이차원 배열

In [7]:
arr2 =np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#배열의 형태(행,열)
arr2.shape

(2, 3)

In [9]:
#배열의 요소 전체 개수
arr2.size

6

In [10]:
#배열의 데이터 타입(자료형 확인)
arr2.dtype
# int32 => 32는 bit를 뜻함(기계가 표현할 수 있는 범위) 2^32
# int8 => 1비트 당 2개의 숫자를 표현할 수 있음 2^8 =256개 표현 가능
# int32 => -2,147,483,648 ~ 2,147,483,647\narr2.size","execution_count":20,"outputs":[{"output_type":"execute_result","execution_count":20,"data":{"text/plain":"6"},"metadata":{}}]}]

dtype('int32')

In [11]:
#예제3
arr3 =np.array([[ [1,2],[3,4] ],[[5,6] ,[7,8] ]])


arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
print("배열의형태",arr3.shape)
print("배열의형태",arr3.dtype)
print("배열의형태",arr3.size)

배열의형태 (2, 2, 2)
배열의형태 int32
배열의형태 8


In [13]:
#0으로 배열 생성 
arr_zeros = np.zeros((3,4))
arr_zeros 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#1로 배열 생성 
arr_ones = np.ones((2,4,3))
arr_ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [15]:
#특정값으로 배열 생성하기
arr_full = np.full((5,5),2) #5행 5열의 배열을 2로 채워준다.
arr_full

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

### 다차원 배열 생성에 유용한 함수
-arange 함수로 배열을 생성하고 reshape 함수로 배열의 형태를 바꿔보자!

In [16]:
# 1~50까지 1씩 증가하는 값을 리스트로 만들기
i=[]
for k in range(1,51,1):
    i.append(k)
print(i)
#만든 리스트로 배열 생성하기
np.array(i)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
#반복문을 활용하지 않고 배열 생성
arr5=np.arange(1,51,1)
arr5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [18]:
#arange 함수를 사용해서 1~51까지 중에서 1,11,21,31,41 배열을 생성해주세요
arr6=np.arange(1,52,10)
arr6

array([ 1, 11, 21, 31, 41, 51])

In [19]:
arr7 = np.arange(1,51,1)
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [20]:
#reshape: 배열의 행과 열을 변경시켜 주는 명령
arr7.reshape(5,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [21]:
arr7 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [22]:
#arr7을 출력했을때 형태가 변한 값을 저장하려면 arr7에 대입해준다
arr7 = arr7.reshape(5,10)

In [23]:
#실수 값을 가지는 배열 생성
arr8 = np.array([1,2,2.3,3.4])
arr8

array([1. , 2. , 2.3, 3.4])

In [24]:
#배열의 자료형을 정수형으로 변경해서 출력
arr8 = np.array([1.2,2.3,3.4],dtype=np.int64)
arr8

array([1, 2, 3], dtype=int64)

In [25]:
arr9 = np.array(['1','2','3'],dtype=np.int64)
arr9

array([1, 2, 3], dtype=int64)

### 랜덤(난수)값 생성!

In [26]:
#랜덤한 값으로 배열 생성하기
arr10=np.random.rand(2,3) #6개(2행x3열)값을 랜덤으로 생성 (0~1)
arr10

array([[0.53781191, 0.4972381 , 0.89325349],
       [0.91760134, 0.55938046, 0.72051506]])

In [27]:
#랜덤 정수 값 출력
arr11 = np.random.randint(10) #0~9까지 10개 숫자 중에서 랜덤으로 정수 생성
arr11

8

In [28]:
# 랜덤값 정수형 배열 생성하기
arr12 = np.random.randint(5,size=10)
arr12

array([2, 3, 1, 2, 0, 0, 0, 4, 2, 2])

In [29]:
arr13 = np.random.randint(5,size=(2,3))
arr13

array([[2, 4, 4],
       [0, 4, 3]])

### array 연산

In [30]:
arr14 = np.array([[1,2],[3,4]])
arr14

array([[1, 2],
       [3, 4]])

In [31]:
arr14+arr14 #같은 자리에 있는 값들이 더해져서 출력

array([[2, 4],
       [6, 8]])

In [32]:
list14 =[[1,2],[3,4]]
list14

[[1, 2], [3, 4]]

In [33]:
list14+list14 #리스트는 값이 이어져서 출력된다!

[[1, 2], [3, 4], [1, 2], [3, 4]]

In [34]:
arr14-arr14 

array([[0, 0],
       [0, 0]])

In [35]:
arr14*arr14 

array([[ 1,  4],
       [ 9, 16]])

In [36]:
arr14%arr14 

array([[0, 0],
       [0, 0]], dtype=int32)

In [37]:
arr14/arr14 

array([[1., 1.],
       [1., 1.]])

In [38]:
(arr14+arr14)*8

array([[16, 32],
       [48, 64]])

### numpy 배열의 접근은 어떻게 할까?
- 리스트와 마찬가지로 인덱싱, 슬라이싱을 지원함!

### numpy 배열 인덱싱
- 배열 중 하나의 인데스 값에 있는 데이터를 가져오는 것

In [39]:
arr16 = np.array([[1,2,3],[4,5,6]])
arr16

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr16[0]

array([1, 2, 3])

In [41]:
arr16[0][1]

2

### numpy 슬라이싱
- 배열의 범위를 지정하여 여러 개의 데이터를 가져오는 것

In [42]:
arr17 = np.arange(10)
arr17

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr17[3:8]

array([3, 4, 5, 6, 7])

In [44]:
arr18 = np.arange(50).reshape(5,10)
arr18

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
# 0번, 1번 인덱스 행의 모든 열을 출력(arr18[행의 범위, 열의 범위])
arr18[0:2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [46]:
# 모든 행의 0번 인덱스를 출력
arr18[:,0]

array([ 0, 10, 20, 30, 40])

In [47]:
arr18[:,0:2]

array([[ 0,  1],
       [10, 11],
       [20, 21],
       [30, 31],
       [40, 41]])

In [48]:
arr18[:4,:5]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [49]:
arr19 = np.arange(18).reshape(3,6)
arr19

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [50]:
# 방법 1
arr19[1:,[1,3,5]]

array([[ 7,  9, 11],
       [13, 15, 17]])

In [51]:
#방법 2
arr19[1:, 1: :2] #시작 인덱스: 끝 인덱스: 증감량

array([[ 7,  9, 11],
       [13, 15, 17]])

In [52]:
arr19

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [53]:
#전치(trasposition): 배열의 행과 열의 바꿔주는 것
arr19.T 

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])

In [54]:
arr19

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [55]:
arr19 =arr19.T
arr19

array([[ 0,  6, 12],
       [ 1,  7, 13],
       [ 2,  8, 14],
       [ 3,  9, 15],
       [ 4, 10, 16],
       [ 5, 11, 17]])